### ISSUE TITLE
Move invoices to car fix tracker

### ISSUE THREAD

**Issue by duchacekjan** [duchacekjan/JgsCarFixTracker#62]
- [ ] [Printing example/tutorial](https://medium.com/@Idan_Co/angular-print-service-290651c721f9)
- [ ] Communication with ares
- [ ] Data structure - migration SQLite to Firebase
- [ ] UI/UX design
